defaults: &defaults
  redis_port: 6379
  redis_db: 10
  redis_host: localhost
  redis_namespace: i18n
  redis_pw:

development:
  <<: *defaults
  redis_db: 11

test:
  <<: *defaults
  redis_db: 12

qa:
  <<: *defaults
  redis_pw: 826e8d4875767d4d8dc8935fb35d9d21
  redis_host: icefish.redistogo.com
  redis_port: 9390
  redis_un: redistogo

production:
  <<: *defaults
  redis_db: 10
