defaults: &defaults
  redis_port: 6379
  redis_db: 10
  redis_host: localhost
  redis_namespace: i18n
  redis_url:

development:
  <<: *defaults
  redis_db: 11

test:
  <<: *defaults
  redis_db: 12

qa:
  <<: *defaults
  redis_url: redis://redistogo:826e8d4875767d4d8dc8935fb35d9d21@icefish.redistogo.com:9390

production:
  <<: *defaults
  redis_db: 10
