defaults: &defaults
  redis_port: 6379
  redis_db: 10
  redis_host: localhost
  redis_namespace: i18n

development:
  <<: *defaults
  redis_db: 11

test:
  <<: *defaults
  redis_db: 12

production:
  <<: *defaults
  redis_db: 10
