defaults: &defaults
  redis_port: 6379
  redis_db: 10
  redis_host: localhost
  redis_namespace: i18n
  redis_pw:

development:
  <<: *defaults
  redis_db: 11

test:
  <<: *defaults
  redis_db: 12

qa:
  <<: *defaults
  redis_pw: bc90b6e78f7ee2a2039551f52a044dfd
  redis_host: icefish.redistogo.com
  redis_port: 9390
  redis_un: redistogo
  redis_db:
  redis_namespace:

staging:
  <<: *defaults
  redis_db: 13

demo:
  <<: *defaults
  redis_db: 10
  
production:
  <<: *defaults
  redis_db: 10
