defaults: &defaults
  redis_port: 6379
  redis_db: 10
  redis_host: localhost
  redis_namespace: i18n
  redis_pw:

development:
  <<: *defaults
  redis_db: 11

test:
  <<: *defaults
  redis_db: 12

qa:
  <<: *defaults
  redis_pw: bc90b6e78f7ee2a2039551f52a044dfd
  redis_host: icefish.redistogo.com
  redis_port: 9390
  redis_un: redistogo
  redis_db:
  redis_namespace:

# demo runs in 'staging' environment so staging, demo, and production all point at same redis server
staging:
  <<: *defaults
  redis_db: 6
  #redis_host: utilip, but can't commit to public github

# same as production so that the webdevs can use translatable.g5search.com for both production and demo translations
demo:
  <<: *defaults
  redis_db: 6
  #redis_host: utilip, but can't commit to public github

production: 
  <<: *defaults
  redis_db: 6

